apiVersion: v1
kind: Namespace
metadata:
  name: web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: web-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # One extra pod allowed during update
      maxUnavailable: 1  # One pod can be down during update
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
        # These tell Prometheus to scrape this pod
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: web-app
        image: tktucker/web-app:v1
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
spec:
  type: NodePort
  selector:
    app: web-app  # This matches the label on your Pods
  ports:
    - protocol: TCP
      port: 5000       # The port used to reach the service inside the cluster
      targetPort: 5000 # The port your container is listening on (0.0.0.0:5000)
      nodePort: 30007  # The port used to reach the service from outside the cluster
